name: 'FibBot GitHub Action'

description: 'A GitHub Action to calculate Fibonacci numbers for PR content and post the results as a comment.'

inputs:
  enable_fib:
    description: 'Flag to enable Fibonacci calculation (true/false)'
    required: true
    default: 'false'
  max_threshold:
    description: 'Maximum number for Fibonacci calculation'
    required: true
    default: '1000'

runs:
  using: 'docker'
  image: 'rust:latest'
  args: |
    cargo build --release
    ./target/release/fibbot-action
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PR_URL: ${{ github.event.pull_request.url }}
