name: FibBot Action - Hello World

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fibbot-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build FibBot action inside Docker
        uses: docker://rust:latest
        with:
          args: cargo build --release

      - name: Run FibBot action inside Docker with parameters
        uses: docker://rust:latest
        with:
          args: |
            cargo run --release
        env:
          INPUT_ENABLE_FIB: 'true'
          INPUT_MAX_THRESHOLD: '1000'

      - name: Output "Hello, World!" from FibBot Action
        run: echo "Hello, World!"
