name: FibBot Action - Hello World

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fibbot-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build FibBot action inside Docker
        uses: docker://rust:latest
        with:
          args: cargo build --release

      - name: Run FibBot action inside Docker
        uses: docker://rust:latest
        with:
          args: ./target/release/fibbot-action

      - name: Output "Hello, World!" from FibBot Action
        run: echo "Hello, World!"
