name: FibBot Action - Hello World

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fibbot-action:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust Environment
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.64.0

      - name: Build FibBot Rust Project
        run: |
          cargo build --release

      - name: Run FibBot Action
        run: |
          ./target/release/fibbot-action

      - name: Output "Hello, World!" from FibBot Action
        run: echo "Hello, World!"  # This will show up in logs to verify

